language: go

sudo: required

addons:
  apt:
    packages:
    - libpcap-dev
env:
  - CSPLOIT_CONFIG="${TRAVIS_BUILD_DIR}/config.json"

notifications:
  slack:
    rooms:
      - csploit:BYr15dcnal0Dm6UZRafBqWSC#travis

services:
  - docker

script:
  - docker build -t csploit .
  - docker run -d csploit
  - docker ps -a
  - go build -v
  - go test -v ./...
  - go test -v ./tools/...
